Mission1_WebApp/Models/CalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission1_WebApp.Models
{
    public class CalculatorModel
    {
        [Required]
        [Range(0, 100)]
        public float Assts { get; set; }

        [Required]
        [Range(0, 100)]
        public float GroupProjects { get; set; }

        [Required]
        [Range(0, 100)]
        public float Quiz { get; set; }

        [Required]
        [Range(0, 100)]
        public float Exam { get; set; }

        [Required]
        [Range(0, 100)]
        public float Intex { get; set; }

    }
}

Mission1_WebApp/Controllers/BlahController.cs
using Microsoft.AspNetCore.Mvc;
using Mission1_WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission1_WebApp.Controllers
{
    public class BlahController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Calculate() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Calculate(CalculatorModel model) 
        {
            return View();
        }
    }
}

Mission1_WebApp/Views/Blah/Calculate.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade Calculator";
}


@model CalculatorModel;

<h2>Final Grade Calculator</h2>
<div class="form-center">
    <form method="post">
        <fieldset style="border-radius: 10px;">
            <label for="assignments">Assignments</label>
            <input type="number" id="assignments" asp-for="Assts"><br><br>
            <label for="group_projects">Group Projects</label>
            <input type="number" id="group_projects" asp-for="GroupProjects"><br><br>
            <label for="quizzes">Quizzes</label>
            <input type="number" id="quizzes" asp-for="Quiz"><br><br>
            <label for="exams">Exams</label>
            <input type="number" id="exams" asp-for="Exam"><br><br>
            <label for="intex">Intex</label>
            <input type="number" id="intex" asp-for="Intex"><br><br>
            <div class="buttonHolder">
                <input value="Calculate" type="submit" id="calculate">
            </div>

            <div asp-validation-summary="All"></div> <!--This line will make it so the data validation code will pop up and say something like "Field Required"-->

        </fieldset>
    </form>
</div>

<script src="~/js/JavaScript1.js"></script>

Mission1_WebApp/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "Mark Vogt Home Page";
}


<h1>Mark Vogt</h1>

<img style="width: 450px; border-radius: 10px;" src="img/fishing.jpg" />
<br>

<div class="ex1">
    <p>
        This is is a change

        The coding scene has always intimidated me so I have already started feeling a little nervous about IS 413.
        I really hope to feel a lot more comfortable with coding after taking this class. I also hope I can start enjoying building website applications more!
    </p>

</div>
<br>

<div class="ex1" style="border-style: solid; border-radius: 10px;">
    <h3><u>My Top 3 Jobs I'm Interested in After Graduation</u></h3>

    <ol>
        <li><b>SalesForce Consultant</b></li>
        <li><b>CyberSecurity Consultant</b></li>
        <li><b>CEO of a self startup</b></li>
    </ol>
</div>
<br>

Mission1_WebApp/Views/Blah/gradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2>Final Grade Calculator</h2>
<div class="form-center">
    <form>
        <fieldset style="border-radius: 10px;">
            <label for="assignments">Assignments</label>
            <input type="number" id="assignments"><br><br>
            <label for="group_projects">Group Projects</label>
            <input type="number" id="group_projects"><br><br>
            <label for="quizzes">Quizzes</label>
            <input type="number" id="quizzes"><br><br>
            <label for="exams">Exams</label>
            <input type="number" id="exams"><br><br>
            <label for="intex">Intex</label>
            <input type="number" id="intex"><br><br>
            <div class="buttonHolder">
                <input value="Calculate" type="button" id="calculate">
            </div>
        </fieldset>
    </form>
</div>

<script src="~/js/Calculator.js"></script>

Mission1_WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link href="~/css/Styles.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap.css.map">
    <link href="~/img/logo.PNG" rel="icon" type="image/png" />
    <style>
        nav {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: darkslategrey;
            width: 230px;
            border-radius: 10px;
        }

        a {
            float: left;
        }

        a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        a:hover {
            background-color: #111;
        }
    </style>
</head>
<body>

    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="Calculate">Grade Calculator</a>
    </nav>

    <div>
        @RenderBody()   
    </div>

    <script src="~/lib/jquery/jquery-3.6.0.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/JavaScript1.js"></script>

</body>
</html>